application:
  applicationName: "web"
  configMap:
    enabled: true
    files:
    - nameSuffix: ""
      data:
        PORT: "4200"
        SECURE_GW_ENDPOINT: "https://gateway-veeru-dev.apps.devtest.41b996e9.kubeapp.cloud/"
        SSO_URL: "https://iam-keycloak-veeru-dev.apps.devtest.41b996e9.kubeapp.cloud/auth/"
        SSO_REALM: "nordmart"
        SSO_CLIENT_ID: "stakater-nordmart-web"
        JAEGER_ENDPOINT: "http://jaeger-collector.istio-system:14268/api/traces"
  deployment:
    imagePullSecrets: nexus-docker-config-forked
    envFrom:
    - type: configmap
      name: ""
    additionalLabels:
      appCategory: "frontend"
    annotations:
    volumes: {}
    image:
      repository: stakater/stakater-nordmart-web
      tag: v0.0.7
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /health
          port: 4200
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /health
          port: 4200
  service:
    ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 4200
  rbac:
    create: true
    serviceAccount:
      create: true
      enabled: true
  route:
    enabled: true

