applicationName: "web"
deployment:
  annotations:
  podLabels:
    app: web
  image:
    repository: stakater/stakater-lab/web
    tag: v0.0.1
  probes:
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /health
        port: 4200
    livenessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /health
        port: 4200
  volumes: {}
  env:
  - name: PORT
    value: "4200"
  - name: SECURE_GW_ENDPOINT
    value: "https://gateway-dev.domain.stakater.com"
  - name: SSO_URL
    value: "https://keycloak-dev.domain.stakater.com/auth"
  - name: SSO_REALM
    value: "nordmart"
  - name: SSO_CLIENT_ID
    value: "stakater-nordmart-web"
  - name: JAEGER_ENDPOINT
    value: "http://jaeger-collector.istio-system:14268/api/traces"
service:
  ports:
  - port: 4200
    name: tcp
    protocol: TCP
    targetPort: 4200
rbac:
  create: true
  serviceAccount:
    create: true
configMap:
  enabled: false
