applicationName: "web"
deployment:
  additionalLabels:
    appCategory: "frontend"
  annotations:
  podLabels:
    app: web
  image:
    repository: stakater/stakater-nordmart-web
    tag: v0.0.7
  probes:
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /health
        port: 4200
    livenessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /health
        port: 4200
  volumes: {}
  env:
  - name: PORT
    value: "4200"
  - name: SECURE_GW_ENDPOINT
    value: "https://gateway-NAMESPACE.DOMAIN"
  - name: SSO_URL
    value: "https://keycloak-NAMESPACE.DOMAIN/auth"
  - name: SSO_REALM
    value: "nordmart"
  - name: SSO_CLIENT_ID
    value: "stakater-nordmart-web"
  - name: JAEGER_ENDPOINT
    value: "http://jaeger-collector.istio-system:14268/api/traces"
service:
  ports:
  - port: 4200
    name: tcp
    protocol: TCP
    targetPort: 4200
rbac:
  create: true
  serviceAccount:
    create: true
configMap:
  enabled: false

ingress:
  enabled: false
  servicePort: 8080
  hosts:
    - web-NAMESPACE.DOMAIN
  annotations: 
    # kubernetes.io/ingress.class: external-ingress
    # ingress.kubernetes.io/rewrite-target: /
    # ingress.kubernetes.io/force-ssl-redirect: true
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
