kind: Service
apiVersion: v1
metadata:
  labels:
    group: com.stakater.platform
    provider: stakater
    version: 0.0.1
    k8sapp: web
    expose: "true"
  name: web
  namespace: {NAMESPACE}
  annotations:
    config.xposer.stakater.com/Domain: stakater.com
    config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-{{.Namespace}}'
    config.xposer.stakater.com/IngressURLTemplate: '{{.Service}}.{{.Domain}}'
    xposer.stakater.com/annotations: |-
      kubernetes.io/ingress.class: external-ingress
      ingress.kubernetes.io/force-ssl-redirect: true
spec:
  selector:
    app: web
  ports:
  - name: web
    port: 4200
    protocol: TCP
    targetPort: 4200